#to get the employee details

#GET http://localhost:4004/EmployeeSRV/Employee HTTP/1.1

#filter 
#GET http://localhost:4004/EmployeeSRV/Employee?$expand=address&$filter=fname eq 'kamal' HTTP/1.1

#single employee details

#GET http://localhost:4004/EmployeeSRV/Employee/423fc5eb-d7eb-4824-85c4-221026c60ddb HTTP/1.1

### Get Employee Along With Address
#GET http://localhost:4004/EmployeeSRV/Employee?$expand=address HTTP/1.1

### Getting the Employee detail


GET http://localhost:4004/v2/EmployeeSRV/Employee HTTP/1.1

### Create Employee
POST http://localhost:4004/EmployeeSRV/Employee HTTP/1.1
Content-Type: application/json

    {
      "fname": "chandra",
      "lName": "Sekhar",
      "gender": "Male",
      "DOB": "1990-02-01",
      "contractStarted": "2012-03-11",
      "email": "shekar@gmail.com",
      "phone": "8564543279"
    }

### Get Employee Along With Address
GET http://localhost:4004/EmployeeSRV/Employee?$expand=address HTTP/1.1


### Get Page navigation (skip)
GET http://localhost:4004/EmployeeSRV/Employee?$expand=address&$top=2&$skip=1 HTTP/1.1

### Get Employee Along With Address

GET http://localhost:4004/v2/EmployeeSRV/Employee?$expand=address HTTP/1.1


GET  HTTP/1.1 http://localhost:4004/V2/EmployeeSRV/Employee?$expand=address HTTP/1.1







